<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="aziiz" name="com.testng.ExceptionTimeOutTest" tests="1" failures="0" timestamp="25 Dec 2018 19:54:50 GMT" time="2.013" errors="1">
  <testcase name="infiniteLoopTest" time="2.013" classname="com.testng.ExceptionTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.ExceptionTimeOutTest.infiniteLoopTest() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2000at java.io.FileOutputStream.writeBytes(Native Method)at java.io.FileOutputStream.write(Unknown Source)at java.io.BufferedOutputStream.flushBuffer(Unknown Source)at java.io.BufferedOutputStream.flush(Unknown Source)at java.io.PrintStream.write(Unknown Source)at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)at java.io.OutputStreamWriter.flushBuffer(Unknown Source)at java.io.PrintStream.newLine(Unknown Source)at java.io.PrintStream.println(Unknown Source)at com.testng.ExceptionTimeOutTest.infiniteLoopTest(ExceptionTimeOutTest.java:11)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- infiniteLoopTest -->
</testsuite> <!-- com.testng.ExceptionTimeOutTest -->
